.\"Manpage for xwm.
.TH XWM 1 "NOVEMBER 2020" Linux "User Manuals"
.SH NAME
xwm \- a tiny XCB floating window manager
.SH SYNOPSIS
.B xwm [-v]
.SH DESCRIPTION
.B xwm
is a tiny floating window manager implemented using
the XCB protocol. Other than
.BR xcb-util-keysyms (1),
xwm relies on third-party tools, which can be
configured or expanded to meet the user's preference.
The default configuration provides support and
command aliases for the
.BR surf (1)
web browser,
.BR st (1)
terminal emulator and
.BR dmenu (1)
application launcher.
.SH OPTIONS
.IP -v
Prints the current xwm version.
.SH DEFAULT KEY BINDINGS
.B xwm
may be controlled from an attached client using a key
combination of a prefix key, the 'Super' (Win) key by
default, followed by a command key.
.PP
The default command key bindings are:
.TS
tab(;);
lb l l.
_
Super;MouseButton1;T{
Raise focused window to top of stack.
T}
_
Super;MouseButton3;T{
Raise focused window to top of stack.
T}
_
Super-MouseButton1;[drag];T{
Interactive window move.
T}
_
Super-MouseButton3;[drag];T{
Interactive window resize.
T}
_
Super;Space;T{
Run launcher menu (default: dmenu_run).
T}
_
Super;Enter;T{
Create new terminal window (default: st).
T}
_
Super;b;T{
Create new browser window (default: surf).
T}
_
Super;f;T{
Full-screen focused window.
T}
_
Super;q;T{
Kill focused window.
T}
_
Super-Shift;q;T{
Quite window manager.
T}
_
.TE
.SH BUGS
No known bugs.
.SH AUTHOR
Michael Czigler <michaelczigler[at]mcpcpc[dot]com>
.SH "SEE ALSO"
.BR libxcb (1),
.BR st (1),
.BR surf (1),
.BR dmenu (1)
